export enum VenueFormat {
  FIVE_VS_FIVE = 'FIVE_VS_FIVE',
  SIX_VS_SIX = 'SIX_VS_SIX',
  SEVEN_VS_SEVEN = 'SEVEN_VS_SEVEN',
  EIGHT_VS_EIGHT = 'EIGHT_VS_EIGHT',
  NINE_VS_NINE = 'NINE_VS_NINE',
  TEN_VS_TEN = 'TEN_VS_TEN',
  ELEVEN_VS_ELEVEN = 'ELEVEN_VS_ELEVEN',
}

